from typing import Any, TypedDict, Optional, Literal
from langgraph.graph import StateGraph, END

from app.agents.persona_router import PersonaRouterAgent
from app.agents.planner import PlannerAgent
from app.agents.scout import ScoutAgent
from app.agents.analyst import AnalystAgent
from app.agents.evaluator import EvaluatorAgent
from app.agents.narrator import NarratorAgent


# ─── v2 Investigation State ───────────────────────────────────────────────────

class InvestigationState(TypedDict):
    """Full state flowing through the v2 investigation pipeline."""
    # Input
    repo_url: str
    user_context: Any            # Free-text intent or structured user context

    # Persona & planning
    persona_mode: str            # SOLO_DEV | STARTUP | ENTERPRISE | OSS_MAINTAINER
    persona_confidence: float
    task_graph: dict             # Generated by PlannerAgent

    # Module outputs - populated by Scout
    scout_data: dict             # Git intelligence + AST + risk + issues + web
    structure: dict              # AST structural analysis
    history: dict                # Git patterns & commit history
    community: dict              # Issue/PR mining data
    risk_points: dict            # Static risk scan
    bus_factor_map: dict         # File-level ownership

    # Analysis outputs - populated by Analyst
    analysis: dict               # LLM hypothesis + confidence
    cui_scores: dict             # CUI v2 per-component breakdown
    onboarding_graph: dict       # DAG of files to learn
    ocs_score: int               # Onboarding Complexity Score
    business_risk: dict          # BusinessRiskScorer output

    # Evaluation outputs - populated by Evaluator
    verified_claims: dict        # Verified vs flagged claims
    evaluation_confidence_delta: int

    # Report
    report: dict                 # Final narrative report

    # Control flow
    confidence: int
    needs_web_search: bool
    web_search_done: bool
    current_round: int
    max_rounds: int
    messages: list


class Coordinator:
    """Coordinator v2 — orchestrates the 6-agent pipeline via LangGraph.

    Pipeline: PersonaRouter → Planner → Scout → Analyst → Evaluator → Narrator
    With a conditional loop back to Scout if confidence < threshold.
    """

    def __init__(self, progress_callback=None):
        self.progress_callback = progress_callback

        # Instantiate all agents
        self.persona_router = PersonaRouterAgent(progress_callback)
        self.planner = PlannerAgent(progress_callback)
        self.scout = ScoutAgent(progress_callback)
        self.analyst = AnalystAgent(progress_callback)
        self.evaluator = EvaluatorAgent(progress_callback)
        self.narrator = NarratorAgent(progress_callback)

        self.workflow = self._build_workflow()

    def emit_progress(self, message: str, data: dict = None):
        if self.progress_callback:
            self.progress_callback("coordinator", message, data or {})

    # ─── Nodes ────────────────────────────────────────────────────────────────

    def _persona_node(self, state: InvestigationState) -> InvestigationState:
        # Short-circuit on loop iterations — persona already classified from first Scout run
        if state.get("persona_mode"):
            self.emit_progress(f"  ↷ Persona already set: {state['persona_mode']} — skipping re-classification")
            return state

        self.emit_progress("Stage 2/6 — Persona Router (using real repo data from Scout)")

        # Build rich repo_metadata from Scout's actual findings instead of just the URL
        scout_data = state.get("scout_data", {})
        structure = state.get("structure", {})
        community = state.get("community", {})
        github_info = scout_data.get("github_data", {}).get("repo_info") or {}
        github_community_health = scout_data.get("github_data", {}).get("community_health") or {}

        url_parts = state["repo_url"].rstrip("/").split("/")
        repo_metadata = {
            "repo_name": scout_data.get("repo_name") or (url_parts[-1] if url_parts else "unknown"),
            # Real counts from GitHub API / git analysis (not empty defaults)
            "file_count": structure.get("file_count", 0),
            "contributors_count": scout_data.get("contributors_count", 1),
            "stars": github_info.get("stars", 0),
            "forks": github_info.get("forks", 0),
            "open_issues": community.get("open_issues", 0),
            # Community signals from GitHub community health API
            "has_contributing": github_community_health.get("has_contributing", False),
            "has_codeowners": False,  # Not explicitly tracked yet
            # If GitHub API returned repo_info the repo is public/accessible
            "is_public": bool(github_info),
            "is_archived": github_info.get("is_archived", False),
        }

        user_ctx_raw = state.get("user_context", "")
        user_context = (
            {"declared_persona": user_ctx_raw}
            if isinstance(user_ctx_raw, str) and user_ctx_raw
            else (user_ctx_raw if isinstance(user_ctx_raw, dict) else {})
        )
        result = self.persona_router.classify(
            repo_metadata=repo_metadata,
            user_context=user_context or None,
        )
        state["persona_mode"] = result["persona_mode"]
        state["persona_confidence"] = result.get("confidence", 1.0)
        self.emit_progress(
            f"  ✓ Persona: {result['persona_mode']} "
            f"(confidence={result.get('confidence', 1.0):.2f}) "
            f"| signals: {', '.join(result.get('reasoning', [])[:3])}",
            {"confidence": 25},
        )
        return state

    def _planner_node(self, state: InvestigationState) -> InvestigationState:
        # Short-circuit on loop iterations — task graph already built
        if state.get("task_graph"):
            self.emit_progress("  ↷ Task graph already built — skipping re-planning")
            return state

        self.emit_progress("Stage 3/6 — Planner (with real file/language data)")
        # Scout has already run — structure is populated with real file counts and languages
        repo_metadata: dict = {
            "file_count": state.get("structure", {}).get("file_count", 0),
            "languages": list(state.get("structure", {}).get("languages", {}).keys()),
            "has_github_token": bool(getattr(__import__("app.config", fromlist=["settings"]).settings, "GITHUB_TOKEN", None)),
        }
        task_graph = self.planner.create_plan(
            persona_mode=state["persona_mode"],
            repo_metadata=repo_metadata,
        )
        state["task_graph"] = task_graph
        self.emit_progress(
            f"  ✓ Plan created: {len(task_graph.get('steps', []))} steps | "
            f"strategy={task_graph.get('strategy','standard')}",
            {"confidence": 35},
        )
        return state

    def _scout_node(self, state: InvestigationState) -> InvestigationState:
        self.emit_progress("Stage 1/6 — Scout (multi-source intelligence gathering)")
        do_web = state.get("needs_web_search", False) or not state.get("web_search_done", False)

        scout_data = self.scout.investigate(
            repo_url=state["repo_url"],
            include_web_search=do_web,
            persona_mode=state.get("persona_mode", "SOLO_DEV"),
            task_graph=state.get("task_graph", {}),
        )

        # Merge if we have previous scout_data and just did a web search pass
        existing = state.get("scout_data", {})
        if existing and do_web and state.get("web_search_done", False) is False:
            existing["web_search_results"] = scout_data.get("web_search_results", {})
            scout_data = existing

        state["scout_data"] = scout_data
        state["structure"] = scout_data.get("structure", {})
        state["history"] = {
            "total_commits": scout_data.get("total_commits", 0),
            "patterns_detected": scout_data.get("patterns_detected", {}),
            "top_contributors": scout_data.get("top_contributors", []),
        }
        state["community"] = scout_data.get("community", {})
        state["risk_points"] = scout_data.get("risk_points", {})
        state["bus_factor_map"] = scout_data.get("bus_factor_map", {})

        state["current_round"] = state.get("current_round", 0) + 1
        if do_web:
            state["web_search_done"] = True
            state["needs_web_search"] = False

        # Emit a staged confidence so the frontend bar starts moving (15% baseline after scout)
        self.emit_progress(
            f"  ✓ Scout complete — {state['structure'].get('file_count', 0)} files, "
            f"{state['history'].get('total_commits', 0)} commits",
            {"confidence": 15},
        )
        return state

    def _analyst_node(self, state: InvestigationState) -> InvestigationState:
        self.emit_progress("Stage 4/6 — Analyst")
        analysis = self.analyst.analyze(
            scout_data=state["scout_data"],
            previous_analysis=state.get("analysis"),
            persona_mode=state.get("persona_mode", "SOLO_DEV"),
        )
        state["analysis"] = analysis
        state["confidence"] = analysis["confidence"]
        state["cui_scores"] = analysis.get("cui_scores", {})
        state["onboarding_graph"] = analysis.get("onboarding_graph", {})
        state["ocs_score"] = analysis.get("ocs_score", 0)
        state["business_risk"] = analysis.get("business_risk", {})

        # Emit analyst confidence so the bar jumps to the real value
        self.emit_progress(
            f"  ✓ Analysis complete — confidence {analysis['confidence']}%",
            {"confidence": analysis["confidence"]},
        )

        if analysis["confidence"] < 70 and not state.get("web_search_done", False):
            state["needs_web_search"] = True
            self.emit_progress(
                f"  ↳ Confidence {analysis['confidence']}% < 70% — requesting web evidence"
            )
        else:
            state["needs_web_search"] = False
        return state

    def _evaluator_node(self, state: InvestigationState) -> InvestigationState:
        self.emit_progress("Stage 5/6 — Evaluator")
        # Evaluator.evaluate() expects the full state dict
        eval_result = self.evaluator.evaluate(dict(state))
        state["verified_claims"] = eval_result
        state["evaluation_confidence_delta"] = eval_result.get("confidence_delta", 0)
        # Adjust overall confidence
        state["confidence"] = max(
            0, min(100, state["confidence"] + eval_result.get("confidence_delta", 0))
        )
        self.emit_progress(
            f"  ✓ Evaluation: {eval_result.get('status','ok')} | "
            f"delta={eval_result.get('confidence_delta',0):+d} | "
            f"adjusted confidence={state['confidence']}%",
            {"confidence": state["confidence"]},
        )
        return state

    def _narrator_node(self, state: InvestigationState) -> InvestigationState:
        self.emit_progress("Stage 6/6 — Narrator")
        report = self.narrator.generate_report(
            scout_data=state["scout_data"],
            analysis=state["analysis"],
            persona_mode=state.get("persona_mode", "SOLO_DEV"),
        )
        state["report"] = report
        return state

    # ─── Routing logic ────────────────────────────────────────────────────────

    def _should_gather_more_evidence(
        self, state: InvestigationState
    ) -> Literal["scout", "evaluator"]:
        if state.get("current_round", 0) >= state.get("max_rounds", 3):
            self.emit_progress("  Max rounds reached — proceeding to evaluation")
            return "evaluator"

        if (
            state.get("confidence", 0) < 70
            and not state.get("web_search_done", False)
        ):
            self.emit_progress("  Decision: gathering more web evidence")
            state["needs_web_search"] = True
            return "scout"

        self.emit_progress(
            f"  Decision: confidence={state.get('confidence',0)}% — proceeding to evaluation"
        )
        return "evaluator"

    # ─── Workflow construction ─────────────────────────────────────────────────

    def _build_workflow(self) -> StateGraph:
        wf = StateGraph(InvestigationState)

        wf.add_node("scout", self._scout_node)
        wf.add_node("persona_router", self._persona_node)
        wf.add_node("planner", self._planner_node)
        wf.add_node("analyst", self._analyst_node)
        wf.add_node("evaluator", self._evaluator_node)
        wf.add_node("narrator", self._narrator_node)

        # Scout runs FIRST so PersonaRouter and Planner get real repo data
        # (stars, forks, contributors, file counts from GitHub API + AST scan)
        # On confidence-loop iterations, PersonaRouter and Planner short-circuit
        # (persona_mode and task_graph already set), only Scout re-runs for web search.
        wf.set_entry_point("scout")

        wf.add_edge("scout", "persona_router")
        wf.add_edge("persona_router", "planner")
        wf.add_edge("planner", "analyst")
        wf.add_conditional_edges(
            "analyst",
            self._should_gather_more_evidence,
            {"scout": "scout", "evaluator": "evaluator"},
        )
        wf.add_edge("evaluator", "narrator")
        wf.add_edge("narrator", END)

        return wf.compile()

    # ─── Public API ──────────────────────────────────────────────────────────

    def investigate(
        self,
        repo_url: str,
        max_rounds: int = 3,
        user_context: Any = "",
        persona_mode: Optional[str] = None,
    ) -> dict:
        """Run the complete v2 investigation pipeline."""
        self.emit_progress("Neural Archaeologist v2 investigation started")
        self.emit_progress(f"Repository: {repo_url}")

        initial_state: InvestigationState = {
            "repo_url": repo_url,
            "user_context": user_context,
            "persona_mode": persona_mode or "",
            "persona_confidence": 0.0,
            "task_graph": {},
            "scout_data": {},
            "structure": {},
            "history": {},
            "community": {},
            "risk_points": {},
            "bus_factor_map": {},
            "analysis": {},
            "cui_scores": {},
            "onboarding_graph": {},
            "ocs_score": 0,
            "business_risk": {},
            "verified_claims": {},
            "evaluation_confidence_delta": 0,
            "report": {},
            "confidence": 0,
            "needs_web_search": False,
            "web_search_done": False,
            "current_round": 0,
            "max_rounds": max_rounds,
            "messages": [],
        }

        # If caller pre-set persona, skip persona router by patching the routing —
        # still run it so the task graph gets properly built.
        final_state = self.workflow.invoke(initial_state)

        self.emit_progress("Investigation complete!")

        return {
            "report": final_state.get("report", {}),
            "confidence": final_state.get("confidence", 0),
            "rounds_taken": final_state.get("current_round", 0),
            "web_search_performed": final_state.get("web_search_done", False),
            "analysis": final_state.get("analysis", {}),
            "scout_data": final_state.get("scout_data", {}),
            "persona_mode": final_state.get("persona_mode", "SOLO_DEV"),
            "cui_scores": final_state.get("cui_scores", {}),
            "onboarding_graph": final_state.get("onboarding_graph", {}),
            "ocs_score": final_state.get("ocs_score", 0),
            "business_risk": final_state.get("business_risk", {}),
            "verified_claims": final_state.get("verified_claims", {}),
            "task_graph": final_state.get("task_graph", {}),
        }
